# action name
name: action name

# event
on: [push]

# discript jobs
jobs:
  # Job Name
  job:
    # running enviroment
    runs-on: ubuntu-latest
    # running steps
    steps:
      # set proccess name
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -al

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm i
      - run: npm run test
      - run: echo test done!
